-- 코드를 작성해주세요
SELECT PARENT.ID, IFNULL(COUNT(CHILD.PARENT_ID), 0) AS CHILD_COUNT
FROM ECOLI_DATA AS PARENT
LEFT OUTER JOIN ECOLI_DATA AS CHILD
ON CHILD.PARENT_ID = PARENT.ID
GROUP BY PARENT.ID, CHILD.PARENT_ID
ORDER BY PARENT.ID ASC;