WITH TMP AS (
    SELECT 
        ID, 
        SIZE_OF_COLONY, 
        ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS ROW_INDEX,
        COUNT(*) OVER () AS TOTAL_COUNT
    FROM 
        ECOLI_DATA
)
SELECT 
    ID,
    CASE
        WHEN ROW_INDEX <= TOTAL_COUNT * 0.25 THEN 'CRITICAL'
        WHEN ROW_INDEX <= TOTAL_COUNT * 0.5 THEN 'HIGH'
        WHEN ROW_INDEX <= TOTAL_COUNT * 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM 
    TMP
ORDER BY 
    ID;
