WITH TMP AS (SELECT RI.REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS RI
JOIN REST_REVIEW AS RR
ON RI.REST_ID = RR.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID)

SELECT FI.REST_ID, FI.REST_NAME, FI.FOOD_TYPE, FI.FAVORITES, FI.ADDRESS, TMP.SCORE
FROM REST_INFO AS FI
JOIN TMP
ON FI.REST_ID = TMP.REST_ID
ORDER BY TMP.SCORE DESC, FI.FAVORITES DESC;