SELECT T.ID
FROM ECOLI_DATA AS T
JOIN
    (SELECT E.ID
    FROM ECOLI_DATA AS E
    JOIN
        (select ID, PARENT_ID from ECOLI_DATA WHERE PARENT_ID IS NULL) AS F
    ON
        E.PARENT_ID = F.ID) AS S
ON T.PARENT_ID = S.ID
ORDER BY T.ID;