WITH TMP AS (SELECT CAR_ID, (
    CASE
        WHEN START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16' THEN 1
        ELSE 0
    END) AS B
from CAR_RENTAL_COMPANY_RENTAL_HISTORY)

SELECT CAR_ID, 
    CASE
        WHEN SUM(B) > 0 THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM TMP
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;