WITH O AS (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
FROM FOOD_ORDER AS FO
WHERE DATE_FORMAT(PRODUCE_DATE, '%y-%m') ='22-05'
GROUP BY PRODUCT_ID)

SELECT O.PRODUCT_ID, P.PRODUCT_NAME, (O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM O
JOIN FOOD_PRODUCT AS P
ON O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID ASC;