WITH ID_2021 AS (
SELECT UI.USER_ID
FROM USER_INFO AS UI
WHERE YEAR(UI.JOINED) = 2021),

USERS_2021 AS (SELECT COUNT(*) AS TOTAL_USERS
FROM ID_2021)

SELECT TMP.YEAR, TMP.MONTH, COUNT(TMP.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(TMP.USER_ID) / (SELECT COUNT(*) AS TOTAL_USERS FROM ID_2021), 1) AS PUCHASED_RATIO
FROM (
    SELECT OS.USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE AS OS
    GROUP BY YEAR, MONTH, OS.USER_ID) AS TMP
JOIN ID_2021
ON TMP.USER_ID = ID_2021.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
