-- 2022년도 평가 점수가 가장 높은 사원들의 
-- 점수, 사번, 성명, 직책, 이메일을 조회하는 SQL문
-- 2022년도의 평가 점수는 상,하반기 점수의 합을 의미
-- 평가 점수를 나타내는 컬럼의 이름은 SCORE
-- HR_DEPARTMENT DEPT_ID, DEPT_NAME_KR, DEPT_NAME_EN, LOCATION
-- HR_EMPLOYEES EMP_NO, EMP_NAME, DEPT_ID, POSITION, EMAIL, COMP_TEL, HIRE_DATE, SAL
-- HR_GRADE EMP_NO, YEAR, HALF_YEAR, SCORE

select SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE AS G
JOIN HR_EMPLOYEES AS E
ON G.EMP_NO = E.EMP_NO
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;