SELECT p.ID, p.NAME, p.HOST_ID
FROM PLACES p
JOIN (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(ID) >= 2
) AS heavy_users 
ON p.HOST_ID = heavy_users.HOST_ID
ORDER BY p.ID;
